export JAVA_HOME=/usr/lib/jvm/jre-openjdk
export HBASE_MANAGES_ZK=false
export HBASE_LOG_DIR=/opt/hbase/logs
export HBASE_PID_DIR=/tmp

MASTER_HEAP_MB="${HBASE_MASTER_HEAPSIZE:-512}"
RS_HEAP_MB="${HBASE_RS_HEAPSIZE:-512}"

export HBASE_MASTER_OPTS="${HBASE_MASTER_OPTS} -Xms${MASTER_HEAP_MB}m -Xmx${MASTER_HEAP_MB}m"
export HBASE_REGIONSERVER_OPTS="${HBASE_REGIONSERVER_OPTS} -Xms${RS_HEAP_MB}m -Xmx${RS_HEAP_MB}m"
